django_forms/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'django_forms.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^market_list/', include('market_list.urls', namespace='market_list')),
    url(r'^admin/', include(admin.site.urls)),
]

market_list/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^fill/', views.fill_market_list, name='fill_market_list'),
    url(r'^submit/', views.submit_request, name='submit_request')
]

market_list/models.py
from django.db import models


# Create your models here.
class InsuranceQuote(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField()

    def __str__(self):
        return " ".join([str(self.name), str(self.price)])


class CompetitionRequest(models.Model):
    FALLBACK_RULES = (
        ('SH', 'Shift'),
        ('WD', 'Withdraw')
    )
    name = models.CharField(max_length=200)
    working_price = models.IntegerField()
    target_position = models.IntegerField()
    fallback_rule = models.CharField(max_length=2, choices=FALLBACK_RULES)
    max_working_price_reduction = models.FloatField()
    working_price_reduction_interval = models.FloatField()

    def __str__(self):
        return "{0}, {1} EUR, Pos {2}".format(self.name, self.working_price,
                                              self.target_position)


def fill_default_market_list():
    InsuranceQuote.objects.all().delete()

    a = InsuranceQuote(name="Aachener", price=44.)
    a.save()

    b = InsuranceQuote(name="Berliner", price=45.)
    b.save()

    c = InsuranceQuote(name="Chemnitzer", price=46)
    c.save()

    d = InsuranceQuote(name="Dortmunder", price=47.)
    d.save()


def process_competition_request(comp_req):
    """ Sort request into market list

    :param request CompetitionReqeuest:
    :return:
    """
    market_data = InsuranceQuote.objects.order_by('price')

    if not market_data:
        # empty list?
        new_entry = InsuranceQuote(comp_req.name, comp_req.working_price)
        new_entry.save()

    for position, entry in enumerate(market_data):
        if position == comp_req.target_position:
            if comp_req.working_price - comp_req.max_working_price_reduction < entry.price:
                # it is possible to reduce
                new_price = comp_req.working_price
                while new_price >= entry.price:
                    new_price = new_price - comp_req.working_price_reduction_interval
                new_entry = InsuranceQuote(name=comp_req.name, price=new_price)
                new_entry.save()
                break  # all done
            else:
                # fail. fallback?
                if comp_req.fallback_rule == 'SH':
                    comp_req.target_position += 1
                    if comp_req.target_position == len(market_data):
                        # no one to compare to, end of the list
                        new_entry = InsuranceQuote(name=comp_req.name, price=comp_req.working_price)
                        new_entry.save()
                        break
                    else:
                        process_competition_request(comp_req)
                        break
                else:
                    break

market_list/forms.py
from django import forms
from .models import CompetitionRequest


class CompetitionRequestForm(forms.ModelForm):
    class Meta:
        model = CompetitionRequest
        fields = '__all__'

market_list/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse

from .models import InsuranceQuote, fill_default_market_list, process_competition_request
from .forms import CompetitionRequestForm


def get_context():
    list = InsuranceQuote.objects.order_by('price')
    defaults = {'name': "Muenchner",
                'working_price': 50,
                'target_position': 0,
                'fallback_rule': 'SH',
                'working_price_reduction_interval': 0.01,
                'max_working_price_reduction': 10
                }
    form = CompetitionRequestForm(initial=defaults)
    context = {'list': list, 'form': form}
    return context


def index(request):
    return render(request, 'market_list/index.html', get_context())


def fill_market_list(request):
    fill_default_market_list()
    return HttpResponseRedirect(reverse('market_list:index'), get_context())


def submit_request(request):
    if request.method == 'POST':
        form = CompetitionRequestForm(request.POST)
        if form.is_valid():
            process_competition_request(form.instance)

    return HttpResponseRedirect(reverse('market_list:index'), get_context())

market_list/templates/market_list/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>InsurTec Demo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>


<div class="container">
    <h1>Margin and Competition Optimization (work in progress)</h1>

    <h2>Demo Price Comparison List</h2>

    {% if list %}
        <table class="table table-striped">
            <tr><th>Position</th><th>Name</th><th>Price</th></tr>
        {% for entry in list %}
            <tr>
            <td>{{ forloop.counter0 }}</td><td> {{ entry.name }}</td><td>{{ entry.price }}</td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>No market entries are available.</p>
    {% endif %}

    <form action="{% url 'market_list:fill_market_list' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Reset table to default"/>
    </form>

<hr/>

    <h2>Input Competition Request Here</h2>

    <form action="{% url 'market_list:submit_request' %}" method="post">
        {% csrf_token %}
        <table class="table">
        {{ form.as_table }}
        <tr><td></td><td><input type="submit" value="Submit"/></td></tr>
        </table>
    </form>

</div>


</body>
</html>